import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is never rendered — the ruler strip handles chapter navigation
 * and the pager comes from src/data/chapters.ts. It exists only because the
 * docs plugin requires one.
 *
 * Autogenerated from sidebar_position in each chapter's frontmatter, so
 * reading order is declared in the files themselves and there is nothing
 * here to drift.
 */
const sidebars: SidebarsConfig = {
  guide: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
